### ISSUE TITLE
Add PHP-Yaml Module

### ISSUE THREAD

**Issue by vasqueeg** [vagnercardosoweb/docker-php8#10]
Hello @vagnercardosoweb  - Is there a guide on how to add PHP-Yaml Module in the existing docker compose?  Thank you in advance!

**Comment by vagnercardosoweb** [comment]
@vasqueeg 

You just need to add the php extension, I'll add it tomorrow and let you know here.

**Comment by vagnercardosoweb** [comment]
@vasqueeg added support, update with main branch

**Comment by vasqueeg** [comment]
Hello @vagnercardosoweb,

Thanks for the quick action!  Anyway, I've attempted to pull the changes to my machine and stop/start my docker.  However, it seems like yaml module is still not present.

> 587f366fadf5:/var/www/app# php -m
> [PHP Modules]
> apcu
> bcmath
> Core
> ctype
> curl
> date
> dom
> exif
> fileinfo
> filter
> ftp
> gd
> gmp
> hash
> iconv
> imap
> intl
> json
> libxml
> mbstring
> mongodb
> mysqli
> mysqlnd
> openssl
> pcntl
> pcre
> PDO
> pdo_mysql
> pdo_pgsql
> pdo_sqlite
> pgsql
> Phar
> posix
> random
> readline
> redis
> Reflection
> session
> SimpleXML
> soap
> sockets
> sodium
> SPL
> sqlite3
> ssh2
> standard
> sysvmsg
> sysvsem
> sysvshm
> tokenizer
> xdebug
> xml
> xmlreader
> xmlwriter
> xsl
> Zend OPcache
> zip
> zlib
> 
> [Zend Modules]
> Xdebug
> Zend OPcache

The .so file is not present in /usr/local/lib/php/extensions/no-debug-non-zts-20220829/

> 587f366fadf5:/var/www/app# ls -la /usr/local/lib/php/extensions/no-debug-non-zts-20220829/
> total 20428
> drwxr-xr-x    1 root     root          4096 Mar  1 10:40 .
> drwxr-xr-x    1 root     root            39 Oct 28 02:11 ..
> -rw-r--r--    1 root     root        413504 Mar  1 10:39 apcu.so
> -rwxr-xr-x    1 root     root         38864 Mar  1 10:33 bcmath.so
> -rwxr-xr-x    1 root     root         92104 Mar  1 10:34 exif.so
> -rwxr-xr-x    1 root     root        387352 Mar  1 10:34 gd.so
> -rwxr-xr-x    1 root     root         79816 Mar  1 10:36 gmp.so
> -rwxr-xr-x    1 root     root        112584 Mar  1 10:36 imap.so
> -rwxr-xr-x    1 root     root        604352 Mar  1 10:35 intl.so
> -rwxr-xr-x    1 root     root       1225312 Mar  1 10:34 mbstring.so
> -rw-r--r--    1 root     root       9832304 Mar  1 10:39 mongodb.so
> -rwxr-xr-x    1 root     root        174024 Mar  1 10:33 mysqli.so
> -rwxr-xr-x    1 root     root       1031080 Mar  1 10:36 opcache.so
> -rwxr-xr-x    1 root     root         47048 Mar  1 10:35 pcntl.so
> -rwxr-xr-x    1 root     root         34760 Mar  1 10:33 pdo_mysql.so
> -rwxr-xr-x    1 root     root         55240 Mar  1 10:33 pdo_pgsql.so
> -rwxr-xr-x    1 root     root        145352 Mar  1 10:33 pgsql.so
> -rw-r--r--    1 root     root       3569336 Mar  1 10:37 redis.so
> -rwxr-xr-x    1 root     root        338024 Mar  1 10:34 soap.so
> -rwxr-xr-x    1 root     root        108488 Mar  1 10:35 sockets.so
> -rwxr-xr-x    1 root     root        112584 Oct 28 02:11 sodium.so
> -rw-r--r--    1 root     root        302072 Mar  1 10:40 ssh2.so
> -rwxr-xr-x    1 root     root         22472 Mar  1 10:35 sysvmsg.so
> -rwxr-xr-x    1 root     root         14280 Mar  1 10:35 sysvsem.so
> -rwxr-xr-x    1 root     root         18376 Mar  1 10:35 sysvshm.so
> -rw-r--r--    1 root     root       1907024 Mar  1 10:37 xdebug.so
> -rwxr-xr-x    1 root     root         59496 Mar  1 10:34 xml.so
> -rwxr-xr-x    1 root     root         39016 Mar  1 10:35 xsl.so
> -rwxr-xr-x    1 root     root         96200 Mar  1 10:34 zip.so
