### ISSUE TITLE
xdebug not stopping + PhpStorm using port 9000

### ISSUE THREAD

**Issue by urielmx** [vagnercardosoweb/docker-php8#3]
A few weeks ago I used this project as a platform for a simple page and it worked. Today I used it on a different one and this new one does not stop when debugging. The only difference I see is that now there's a single .ini file instead of one for PHP and one for XDEBUG. Also, XDebug section now does not contain `zend_extension = xdebug.so`
Are you able to keep debugging?

NOTE: I also had to change port 9000 to 9002 cause the new version of PhpStorm uses it idk what for.

**Comment by vagnercardosoweb** [comment]
@urielmx Good evening, I made some adjustments, pull the project.

1. The extension is already loaded automatically.
2. I configured PHPStorm.
3. I used port 9003.

For me it worked both with a Server created in PHPStorm and also per individual file.

<img width="985" alt="image" src="https://github.com/vagnercardosoweb/docker-php8/assets/16264950/45f41b59-c858-49a9-9696-f01e622086dc">

<img width="1050" alt="image" src="https://github.com/vagnercardosoweb/docker-php8/assets/16264950/62baed2d-2e5f-4e98-a952-61005478f3a5">

<img width="332" alt="image" src="https://github.com/vagnercardosoweb/docker-php8/assets/16264950/7128d434-dd1d-44dd-bbb8-94684b7768e3">

## Using with VSCODE

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for Xdebug",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "pathMappings": {
        "/var/www": "${workspaceFolder}"
      }
    }
  ]
}
```

<img width="1520" alt="image" src="https://github.com/vagnercardosoweb/docker-php8/assets/16264950/7f5548b3-4826-47a0-b707-dce7c3756abd">

**Comment by urielmx** [comment]
Now it works again. Thanks!
Small note: as I use Mac, I always have to add `platform: linux/x86_64 under` MySQL at docker-compose.yml, otherwise I get this error:
[ "no matching manifest for linux/arm64/v8 in the manifest list entries"](https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8)
If it does not affect other OS, it could be added, too.
Thanks for your fast reply and fixes!
