### ISSUE TITLE
No such file or directory't execute 'bash

### ISSUE THREAD

**Issue by skjamil** [vagnercardosoweb/docker-php8#8]
I am getting No such file or directory't execute 'bash while tried to run the PHP image.

**Comment by vagnercardosoweb** [comment]
@skjamil 

Hello, which operating system and can you send more details?

**Comment by skjamil** [comment]
I have Windows 11 Pro installed. 
Docker version 24.0.6, build ed223bc.
WSL version: 2.0.9.0

**Comment by vagnercardosoweb** [comment]
@skjamil can you send me a print of the logs at the time of the errors so I can debug? I don't have windows/linux.

**Comment by skjamil** [comment]
Sure.
![Screenshot 2024-01-31 225629](https://github.com/vagnercardosoweb/docker-php8/assets/9887400/74cad29c-c1eb-4fd8-863f-4afc96948291)
![Screenshot 2024-01-31 225524](https://github.com/vagnercardosoweb/docker-php8/assets/9887400/1ab29183-ebe5-4d80-ac7c-c292ee640069)

**Comment by vagnercardosoweb** [comment]
@skjamil 

Hi, I haven't had time to test it on Windows/Linux yet, I only use MacOS, I'll test it as soon as possible.

It may be a path that is not recognized in Windows.

As soon as I can test it I'll let you know, if you've managed to adjust it let me know.

**Comment by eduanayardo** [comment]
Hi @skjamil, im add this line on php DockerFile `RUN apk update && apk add bash` after install composer and run this command on console `docker-compose up --build --force-recreate --no-deps php`

> Sure. ![Screenshot 2024-01-31 225629](https://private-user-images.githubusercontent.com/9887400/301251649-74cad29c-c1eb-4fd8-863f-4afc96948291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MjIzNjYsIm5iZiI6MTcwNzQyMjA2NiwicGF0aCI6Ii85ODg3NDAwLzMwMTI1MTY0OS03NGNhZDI5Yy1jMWViLTRmZDgtODYzZi00YWZjOTY5NDgyOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMTk1NDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTEwOTFjMDFmYTc2YzgxNGUyNDA4YTE5Y2I2Yzk3Mjk3MGFhN2UwOWMwYTM1MjFmNGQ1Zjc0MWE4ODI4MGVlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dTtLR5fW5DBbLNXMsZ17HdvERwE8-5iuro_EVeMPMtk) ![Screenshot 2024-01-31 225524](https://private-user-images.githubusercontent.com/9887400/301251661-1ab29183-ebe5-4d80-ac7c-c292ee640069.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MjIzNjYsIm5iZiI6MTcwNzQyMjA2NiwicGF0aCI6Ii85ODg3NDAwLzMwMTI1MTY2MS0xYWIyOTE4My1lYmU1LTRkODAtYWM3Yy1jMjkyZWU2NDAwNjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMTk1NDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmFjNGI5MmMwYzFlZmNmOGVjNTQ0NjgzYzM0Y2Y0YzhlZDJiOTA5NDgxMDU5ZmFmZjAyYWVkNDhmMzk1YzdlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IOsVk83qVMqlLpifSNKW4WKk4Be38WqKusjv9gPMKqE)

**Comment by vagnercardosoweb** [comment]
@eduanayardo and @skjamil 

Thank you for the answer, I confess that I haven't had time to carry out a test on Windows yet, maybe I'll be able to do it at the weekend, but if it works, you can open a PR, thank you very much.

**Comment by eduanayardo** [comment]
Hi Vagner, let me do another test with this change and i make a PR

**Comment by vagnercardosoweb** [comment]
@eduanayardo @skjamil 

Issue closed, if you want to talk about it again, feel free to open another one.
